"""Plugin environment management for project-local Stepyard plugins."""

from __future__ import annotations

import os
import re
import subprocess
import sys

PYPROJECT_TEMPLATE = """[project]
name = "{plugin_name}"
version = "0.1.0"
description = "Stepyard plugin: {plugin_name}"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "stepyard"
]

[project.entry-points."stepyard.plugins"]
{entry_name} = "{package_name}.nodes"

[project.entry-points."stepyard.triggers"]
{entry_name} = "{package_name}.triggers"

[project.entry-points."stepyard.hooks"]
{entry_name} = "{package_name}.hooks"

[project.entry-points."stepyard.input_collectors"]
{entry_name} = "{package_name}.inputs"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
"""

README_TEMPLATE = """# {plugin_name}

Stepyard plugin package generated by `stepyard plugin init`.

## Development

Install this plugin into a Stepyard project:

```bash
stepyard plugin add .
```

Use the sample node in a flow:

```yaml
name: Sample Plugin Flow
steps:
  - id: greet
    uses: sample.greet
    with:
      name: "Stepyard"
```
"""

NODES_TEMPLATE = '''from stepyard.sdk.node import node


@node(name="sample.greet")
def greet(name: str) -> str:
    """Returns a friendly greeting."""
    return f"Hello {name}!"
'''

TRIGGERS_TEMPLATE = '''from datetime import datetime, timedelta
from apscheduler.triggers.date import DateTrigger
from stepyard.sdk.trigger import trigger


@trigger(name="sample.delayed")
def delayed(minutes: int):
    """Fires once after a delayed number of minutes."""
    return DateTrigger(run_date=datetime.now() + timedelta(minutes=minutes))
'''

HOOKS_TEMPLATE = """from typing import Any
from stepyard.sdk.hooks import StepExecutionHook
from stepyard.sdk.node import NodeContext, NodeResult


class SampleHook(StepExecutionHook):
    async def before_execute(self, context: NodeContext, step: Any, inputs: dict[str, Any]) -> NodeResult | None:
        return None

    async def after_execute(self, context: NodeContext, step: Any, result: NodeResult) -> NodeResult:
        return result


hooks = [SampleHook()]
"""

INPUTS_TEMPLATE = """from stepyard.sdk.inputs import InputRequest, input_collector


@input_collector("sample.greet")
def collect_greeting_name(step_id, step, inputs, context):
    return InputRequest(
        step_id=step_id,
        env_key=f"STEPYARD_SAMPLE_GREET_{step_id.upper()}",
        prompt="Name",
        default=str(inputs.get("name", "")),
        required=False,
    )
"""

TEST_TEMPLATE = """from {package_name}.nodes import greet


def test_sample_greet():
    assert greet("Stepyard") == "Hello Stepyard!"
"""


class PluginManager:
    def __init__(self, project_dir: str):
        self.project_dir = os.path.abspath(project_dir)
        self.stepyard_dir = os.path.join(self.project_dir, ".stepyard")
        self.env_dir = os.path.join(self.stepyard_dir, "env")
        self.lockfile_path = os.path.join(self.project_dir, "stepyard.lock")

        if sys.platform == "win32":
            self.venv_python = os.path.join(self.env_dir, "Scripts", "python.exe")
        else:
            self.venv_python = os.path.join(self.env_dir, "bin", "python")

    def get_site_packages(self) -> str:
        """Return the site-packages directory of the project plugin virtualenv."""
        if sys.platform == "win32":
            return os.path.join(self.env_dir, "Lib", "site-packages")
        return os.path.join(
            self.env_dir,
            "lib",
            f"python{sys.version_info.major}.{sys.version_info.minor}",
            "site-packages",
        )

    def ensure_env(self) -> str:
        """Create the project plugin virtual environment if it is missing."""
        if not os.path.exists(self.venv_python):
            os.makedirs(self.stepyard_dir, exist_ok=True)
            subprocess.run(
                [sys.executable, "-m", "venv", self.env_dir],
                check=True,
                capture_output=True,
            )

            mvp_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
            if os.path.exists(os.path.join(mvp_dir, "pyproject.toml")):
                subprocess.run(  # nosec B603
                    [self.venv_python, "-m", "pip", "install", "-e", mvp_dir],
                    check=True,
                    capture_output=True,
                )

            if os.path.exists(self.lockfile_path):
                subprocess.run(  # nosec B603
                    [self.venv_python, "-m", "pip", "install", "-r", self.lockfile_path],
                    check=True,
                    capture_output=True,
                )
        return self.venv_python

    def add_plugin(self, package_spec: str) -> None:
        """Install a plugin package into the project plugin environment."""
        self.ensure_env()
        res = subprocess.run(  # nosec B603
            [self.venv_python, "-m", "pip", "install", package_spec],
            capture_output=True,
            text=True,
        )
        if res.returncode != 0:
            raise RuntimeError(
                f"Failed to install plugin {package_spec}: {res.stderr or res.stdout}"
            )
        self._add_to_lockfile(package_spec)

    def remove_plugin(self, package_name: str) -> None:
        """Uninstall a plugin package from the project plugin environment."""
        self.ensure_env()
        res = subprocess.run(  # nosec B603
            [self.venv_python, "-m", "pip", "uninstall", "-y", package_name],
            capture_output=True,
            text=True,
        )
        if res.returncode != 0:
            raise RuntimeError(
                f"Failed to uninstall plugin {package_name}: {res.stderr or res.stdout}"
            )
        self._remove_from_lockfile(package_name)

    def sync_plugins(self) -> None:
        """Synchronize the project plugin environment from stepyard.lock."""
        self.ensure_env()
        if not os.path.exists(self.lockfile_path):
            return
        res = subprocess.run(  # nosec B603
            [self.venv_python, "-m", "pip", "install", "-r", self.lockfile_path],
            capture_output=True,
            text=True,
        )
        if res.returncode != 0:
            raise RuntimeError(
                f"Failed to sync environment from stepyard.lock: {res.stderr or res.stdout}"
            )

    def _add_to_lockfile(self, package_spec: str) -> None:
        specs = []
        if os.path.exists(self.lockfile_path):
            with open(self.lockfile_path, encoding="utf-8") as f:
                specs = [line.strip() for line in f if line.strip()]

        norm_spec = os.path.abspath(package_spec) if os.path.exists(package_spec) else package_spec
        exists = False
        for spec in specs:
            norm_existing = os.path.abspath(spec) if os.path.exists(spec) else spec
            if norm_existing == norm_spec:
                exists = True
                break

        if not exists:
            specs.append(package_spec)
            with open(self.lockfile_path, "w", encoding="utf-8") as f:
                f.write("\n".join(specs) + "\n")

    def _remove_from_lockfile(self, package_name: str) -> None:
        if not os.path.exists(self.lockfile_path):
            return

        with open(self.lockfile_path, encoding="utf-8") as f:
            specs = [line.strip() for line in f if line.strip()]

        new_specs = []
        for spec in specs:
            if spec == package_name:
                continue

            if os.path.exists(spec) and os.path.isdir(spec):
                pyproject = os.path.join(spec, "pyproject.toml")
                if os.path.exists(pyproject):
                    try:
                        import tomllib

                        with open(pyproject, "rb") as f_in:
                            data = tomllib.load(f_in)
                        name = data.get("project", {}).get("name")
                        if name == package_name:
                            continue
                    except Exception:  # noqa: BLE001 - unreadable pyproject; treat as name mismatch
                        pass

            # Only remove specs whose normalised package name matches exactly.
            # A substring match (e.g. "foo" matching "foo-bar") would silently
            # delete unrelated entries.
            spec_pkg = spec.split("==")[0].split(">=")[0].split("@")[0].strip()
            spec_pkg_norm = spec_pkg.lower().replace("-", "_")
            pkg_norm = package_name.lower().replace("-", "_")
            if spec_pkg_norm == pkg_norm:
                continue
            new_specs.append(spec)

        with open(self.lockfile_path, "w", encoding="utf-8") as f:
            f.write("\n".join(new_specs) + ("\n" if new_specs else ""))

    def init_plugin_template(self, plugin_name: str, dest_dir: str) -> None:
        """Create a publishable starter Stepyard plugin project."""
        target_dir = os.path.abspath(dest_dir)
        os.makedirs(target_dir, exist_ok=True)
        package_name = self._python_package_name(plugin_name)
        entry_name = plugin_name.replace("-", "_")

        self._write_template(
            target_dir,
            "pyproject.toml",
            PYPROJECT_TEMPLATE.format(
                plugin_name=plugin_name,
                entry_name=entry_name,
                package_name=package_name,
            ),
        )
        self._write_template(
            target_dir, "README.md", README_TEMPLATE.format(plugin_name=plugin_name)
        )

        pkg_dir = os.path.join(target_dir, package_name)
        os.makedirs(pkg_dir, exist_ok=True)
        self._write_template(pkg_dir, "nodes.py", NODES_TEMPLATE)
        self._write_template(pkg_dir, "triggers.py", TRIGGERS_TEMPLATE)
        self._write_template(pkg_dir, "hooks.py", HOOKS_TEMPLATE)
        self._write_template(pkg_dir, "inputs.py", INPUTS_TEMPLATE)

        test_dir = os.path.join(target_dir, "tests")
        os.makedirs(test_dir, exist_ok=True)
        self._write_template(
            test_dir, "test_nodes.py", TEST_TEMPLATE.format(package_name=package_name)
        )
        self._write_template(pkg_dir, "__init__.py", "")

    @staticmethod
    def _write_template(directory: str, filename: str, content: str) -> None:
        with open(os.path.join(directory, filename), "w", encoding="utf-8") as f:
            f.write(content)

    @staticmethod
    def _python_package_name(plugin_name: str) -> str:
        package_name = re.sub(r"[^A-Za-z0-9_]", "_", plugin_name).strip("_").lower()
        if not package_name:
            raise ValueError("Plugin name must contain at least one letter, number, or underscore.")
        if package_name[0].isdigit():
            package_name = f"stepyard_plugin_{package_name}"
        return package_name
